version: '3.9'

services:
  db:
    image: postgres:alpine
    restart: always
    container_name: ${APP_NAME}-db
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: ${APP_NAME}-api
    ports:
      - 7001:7001
    env_file:
      - .env
    volumes:
      # - api-data:/usr/src/app
      - .:/usr/src/app
      # - api-node_modules:/usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

volumes:
  db-data:
  api-data:
  api-node_modules:
    driver: local

networks:
  default: