version: '3.9'

services:
  test-db:
    image: postgres:alpine
    restart: always
    container_name: ${APP_NAME}-test-db
    expose:
      - 5432
    ports:
      - 5433:5432
    env_file:
      - .env.test.local
    volumes:
      - test-db-data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5

  test-api:
    build: .
    container_name: ${APP_NAME}-test-api
    ports:
      - 7001:7001
    env_file:
      - .env.test.local
    volumes:
      # - api-data:/usr/src/app
      - .:/usr/src/app
      - api-node_modules:/usr/src/app/node_modules
    depends_on:
      test-db:
        condition: service_healthy
    networks:
      - default

volumes:
  test-db-data:
  api-data:
  api-node_modules:
    driver: local

networks:
  default: